Repository Bruncky/rent-my-ride, pull requests merged in 2020-02, with the labels that each got.

#30 Link views
  app/controllers/application_controller.rb
  app/controllers/users_controller.rb
  app/views/cars/index.html.erb
  app/views/cars/show.html.erb
  app/views/shared/_navbar.html.erb
  config/routes.rb
Labels: pull

#33 add booking values in users show
  app/views/cars/show.html.erb
  app/views/users/show.html.erb
Labels: no-pull

#32 Mapbox
  Gemfile
  Gemfile.lock
  app/controllers/cars_controller.rb
  app/javascript/packs/application.js
  app/javascript/plugins/init_mapbox.js
  app/javascript/plugins/mapbox.js
  app/models/car.rb
  app/views/cars/index.html.erb
  app/views/layouts/application.html.erb
  app/views/pages/home.html.erb
  config/initializers/geocoder.rb
  db/migrate/20200226104038_add_coordinates_to_cars.rb
  db/schema.rb
  package.json
  yarn.lock
Labels: pull

#35 Seed address fix
  app/assets/stylesheets/components/_map.scss
  app/controllers/cars_controller.rb
  app/javascript/plugins/init_mapbox.js
  app/views/cars/_info_window.html.erb
  db/seeds.rb
  san_francisco.jpg
Labels: bundle install, pull, yarn install

#48 refactor mapbox, so it only loads on needed pages
  app/controllers/cars_controller.rb
  app/javascript/packs/application.js
  app/javascript/packs/mapbox.js
  app/views/cars/index.html.erb
  app/views/cars/show.html.erb
  app/views/pages/home.html.erb
Labels: enhancement

#49 Removed extra search submit button
  app/views/pages/home.html.erb
Labels: fix, pull

#65 Search 2.0
  app/controllers/cars_controller.rb
  app/javascript/plugins/search.js
  app/views/pages/home.html.erb
  db/migrate/20200227140429_change_end_date_to_date_time.rb
  db/schema.rb
Labels: pull

#69 Seed change
  Gemfile
  Gemfile.lock
  app/models/car.rb
  app/views/cars/_form.html.erb
  db/seeds.rb
Labels: db:reset
